// This file is auto generated by table_compiler
a_star_helper * a_star_helper_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"node", (char *)"expt", (char *)"traveled", (char *)"prev"};
  static const char * const column_types[] = {"u32", "f32", "f32", "u32"};
  a_star_helper * instance = alloc0(sizeof(a_star_helper));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 4, (u32[]){sizeof(u32), sizeof(f32), sizeof(f32), sizeof(u32)}, (char *[]){(char *)"node", (char *)"expt", (char *)"traveled", (char *)"prev"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void a_star_helper_insert(a_star_helper * table, u32 * node, f32 * expt, f32 * traveled, u32 * prev, u64 count){
  void * array[] = {(void* )node, (void* )expt, (void* )traveled, (void* )prev};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void a_star_helper_set(a_star_helper * table, u32 node, f32 expt, f32 traveled, u32 prev){
  void * array[] = {(void* )&node, (void* )&expt, (void* )&traveled, (void* )&prev};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void a_star_helper_lookup(a_star_helper * table, u32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void a_star_helper_remove(a_star_helper * table, u32 * keys, u64 key_count){
  u64 indexes[key_count];
  u64 index = 0;
  u64 cnt = 0;
  while(0 < (cnt = abstract_sorttable_iter((abstract_sorttable *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, cnt);
    index = 0;
  }
}

void a_star_helper_clear(a_star_helper * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void a_star_helper_unset(a_star_helper * table, u32 key){
  a_star_helper_remove(table, &key, 1);
}

bool a_star_helper_try_get(a_star_helper * table, u32 * node, f32 * expt, f32 * traveled, u32 * prev){
  void * array[] = {(void* )node, (void* )expt, (void* )traveled, (void* )prev};
  void * column_pointers[] = {(void *)table->node, (void *)table->expt, (void *)table->traveled, (void *)table->prev};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u32), sizeof(f32), sizeof(f32), sizeof(u32)};
  for(int i = 1; i < 4; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void a_star_helper_print(a_star_helper * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 a_star_helper_iter(a_star_helper * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
