// This file is auto generated by table_compiler
character_table * character_table_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"entity", (char *)"current_node", (char *)"target_node"};
  static const char * const column_types[] = {"u32", "u32", "u32"};
  character_table * instance = alloc0(sizeof(character_table));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 3, (u32[]){sizeof(u32), sizeof(u32), sizeof(u32)}, (char *[]){(char *)"entity", (char *)"current_node", (char *)"target_node"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void character_table_insert(character_table * table, u32 * entity, u32 * current_node, u32 * target_node, u64 count){
  void * array[] = {(void* )entity, (void* )current_node, (void* )target_node};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void character_table_set(character_table * table, u32 entity, u32 current_node, u32 target_node){
  void * array[] = {(void* )&entity, (void* )&current_node, (void* )&target_node};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void character_table_lookup(character_table * table, u32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void character_table_remove(character_table * table, u32 * keys, u64 key_count){
  u64 indexes[key_count];
  u64 index = 0;
  u64 cnt = 0;
  while(0 < (cnt = abstract_sorttable_iter((abstract_sorttable *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, cnt);
    index = 0;
  }
}

void character_table_clear(character_table * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void character_table_unset(character_table * table, u32 key){
  character_table_remove(table, &key, 1);
}

bool character_table_try_get(character_table * table, u32 * entity, u32 * current_node, u32 * target_node){
  void * array[] = {(void* )entity, (void* )current_node, (void* )target_node};
  void * column_pointers[] = {(void *)table->entity, (void *)table->current_node, (void *)table->target_node};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u32), sizeof(u32), sizeof(u32)};
  for(int i = 1; i < 3; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void character_table_print(character_table * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 character_table_iter(character_table * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
