// This file is auto generated by table_compiler
connected_nodes * connected_nodes_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"n1", (char *)"n2"};
  static const char * const column_types[] = {"u32", "u32"};
  connected_nodes * instance = alloc0(sizeof(connected_nodes));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 2, (u32[]){sizeof(u32), sizeof(u32)}, (char *[]){(char *)"n1", (char *)"n2"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void connected_nodes_insert(connected_nodes * table, u32 * n1, u32 * n2, u64 count){
  void * array[] = {(void* )n1, (void* )n2};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void connected_nodes_set(connected_nodes * table, u32 n1, u32 n2){
  void * array[] = {(void* )&n1, (void* )&n2};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void connected_nodes_lookup(connected_nodes * table, u32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void connected_nodes_remove(connected_nodes * table, u32 * keys, u64 key_count){
  u64 indexes[key_count];
  abstract_sorttable_finds((abstract_sorttable *) table, keys, indexes, key_count);
  abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, key_count);
}

void connected_nodes_clear(connected_nodes * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void connected_nodes_unset(connected_nodes * table, u32 key){
  connected_nodes_remove(table, &key, 1);
}

bool connected_nodes_try_get(connected_nodes * table, u32 * n1, u32 * n2){
  void * array[] = {(void* )n1, (void* )n2};
  void * column_pointers[] = {(void *)table->n1, (void *)table->n2};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u32), sizeof(u32)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void connected_nodes_print(connected_nodes * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 connected_nodes_iter(connected_nodes * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
