// This file is auto generated by table_compiler
connection_entities * connection_entities_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"connectionid", (char *)"entity"};
  static const char * const column_types[] = {"u64", "u32"};
  connection_entities * instance = alloc0(sizeof(connection_entities));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 2, (u32[]){sizeof(u64), sizeof(u32)}, (char *[]){(char *)"connectionid", (char *)"entity"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void connection_entities_insert(connection_entities * table, u64 * connectionid, u32 * entity, u64 count){
  void * array[] = {(void* )connectionid, (void* )entity};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void connection_entities_set(connection_entities * table, u64 connectionid, u32 entity){
  void * array[] = {(void* )&connectionid, (void* )&entity};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void connection_entities_lookup(connection_entities * table, u64 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void connection_entities_remove(connection_entities * table, u64 * keys, u64 key_count){
  u64 indexes[key_count];
  abstract_sorttable_finds((abstract_sorttable *) table, keys, indexes, key_count);
  abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, key_count);
}

void connection_entities_clear(connection_entities * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void connection_entities_unset(connection_entities * table, u64 key){
  connection_entities_remove(table, &key, 1);
}

bool connection_entities_try_get(connection_entities * table, u64 * connectionid, u32 * entity){
  void * array[] = {(void* )connectionid, (void* )entity};
  void * column_pointers[] = {(void *)table->connectionid, (void *)table->entity};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u64), sizeof(u32)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void connection_entities_print(connection_entities * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 connection_entities_iter(connection_entities * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
