// This file is auto generated by table_compiler
f32_to_u32_lookup * f32_to_u32_lookup_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key", (char *)"value"};
  static const char * const column_types[] = {"f32", "u32"};
  f32_to_u32_lookup * instance = alloc0(sizeof(f32_to_u32_lookup));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 2, (u32[]){sizeof(f32), sizeof(u32)}, (char *[]){(char *)"key", (char *)"value"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void f32_to_u32_lookup_insert(f32_to_u32_lookup * table, f32 * key, u32 * value, u64 count){
  void * array[] = {(void* )key, (void* )value};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void f32_to_u32_lookup_set(f32_to_u32_lookup * table, f32 key, u32 value){
  void * array[] = {(void* )&key, (void* )&value};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void f32_to_u32_lookup_lookup(f32_to_u32_lookup * table, f32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void f32_to_u32_lookup_remove(f32_to_u32_lookup * table, f32 * keys, u64 key_count){
  u64 indexes[key_count];
  u64 index = 0;
  u64 cnt = 0;
  while(0 < (cnt = abstract_sorttable_iter((abstract_sorttable *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, cnt);
    index = 0;
  }
}

void f32_to_u32_lookup_clear(f32_to_u32_lookup * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void f32_to_u32_lookup_unset(f32_to_u32_lookup * table, f32 key){
  f32_to_u32_lookup_remove(table, &key, 1);
}

bool f32_to_u32_lookup_try_get(f32_to_u32_lookup * table, f32 * key, u32 * value){
  void * array[] = {(void* )key, (void* )value};
  void * column_pointers[] = {(void *)table->key, (void *)table->value};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(f32), sizeof(u32)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void f32_to_u32_lookup_print(f32_to_u32_lookup * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 f32_to_u32_lookup_iter(f32_to_u32_lookup * table, f32 * keys, size_t keycnt, f32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
