// This file is auto generated by table_compiler
game_events * game_events_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"id", (char *)"event"};
  static const char * const column_types[] = {"u32", "game_event"};
  game_events * instance = alloc0(sizeof(game_events));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 2, (u32[]){sizeof(u32), sizeof(game_event)}, (char *[]){(char *)"id", (char *)"event"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void game_events_insert(game_events * table, u32 * id, game_event * event, u64 count){
  void * array[] = {(void* )id, (void* )event};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void game_events_set(game_events * table, u32 id, game_event event){
  void * array[] = {(void* )&id, (void* )&event};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void game_events_lookup(game_events * table, u32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void game_events_remove(game_events * table, u32 * keys, u64 key_count){
  u64 indexes[key_count];
  abstract_sorttable_finds((abstract_sorttable *) table, keys, indexes, key_count);
  abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, key_count);
}

void game_events_clear(game_events * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void game_events_unset(game_events * table, u32 key){
  game_events_remove(table, &key, 1);
}

bool game_events_try_get(game_events * table, u32 * id, game_event * event){
  void * array[] = {(void* )id, (void* )event};
  void * column_pointers[] = {(void *)table->id, (void *)table->event};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u32), sizeof(game_event)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void game_events_print(game_events * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 game_events_iter(game_events * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
