// This file is auto generated by table_compiler
node_action_table * node_action_table_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"id", (char *)"action"};
  static const char * const column_types[] = {"u32", "ui_node_action"};
  node_action_table * instance = alloc0(sizeof(node_action_table));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 2, (u32[]){sizeof(u32), sizeof(ui_node_action)}, (char *[]){(char *)"id", (char *)"action"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void node_action_table_insert(node_action_table * table, u32 * id, ui_node_action * action, u64 count){
  void * array[] = {(void* )id, (void* )action};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void node_action_table_set(node_action_table * table, u32 id, ui_node_action action){
  void * array[] = {(void* )&id, (void* )&action};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void node_action_table_lookup(node_action_table * table, u32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void node_action_table_remove(node_action_table * table, u32 * keys, u64 key_count){
  u64 indexes[key_count];
  abstract_sorttable_finds((abstract_sorttable *) table, keys, indexes, key_count);
  abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, key_count);
}

void node_action_table_clear(node_action_table * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void node_action_table_unset(node_action_table * table, u32 key){
  node_action_table_remove(table, &key, 1);
}

bool node_action_table_try_get(node_action_table * table, u32 * id, ui_node_action * action){
  void * array[] = {(void* )id, (void* )action};
  void * column_pointers[] = {(void *)table->id, (void *)table->action};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u32), sizeof(ui_node_action)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void node_action_table_print(node_action_table * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 node_action_table_iter(node_action_table * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
