// This file is auto generated by table_compiler
nr_ui_item * nr_ui_item_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key", (char *)"position"};
  static const char * const column_types[] = {"u32", "vec2"};
  nr_ui_item * instance = alloc0(sizeof(nr_ui_item));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 2, (u32[]){sizeof(u32), sizeof(vec2)}, (char *[]){(char *)"key", (char *)"position"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void nr_ui_item_insert(nr_ui_item * table, u32 * key, vec2 * position, u64 count){
  void * array[] = {(void* )key, (void* )position};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void nr_ui_item_set(nr_ui_item * table, u32 key, vec2 position){
  void * array[] = {(void* )&key, (void* )&position};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void nr_ui_item_lookup(nr_ui_item * table, u32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void nr_ui_item_remove(nr_ui_item * table, u32 * keys, u64 key_count){
  u64 indexes[key_count];
  u64 index = 0;
  u64 cnt = 0;
  while(0 < (cnt = abstract_sorttable_iter((abstract_sorttable *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, cnt);
    index = 0;
  }
}

void nr_ui_item_clear(nr_ui_item * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void nr_ui_item_unset(nr_ui_item * table, u32 key){
  nr_ui_item_remove(table, &key, 1);
}

bool nr_ui_item_try_get(nr_ui_item * table, u32 * key, vec2 * position){
  void * array[] = {(void* )key, (void* )position};
  void * column_pointers[] = {(void *)table->key, (void *)table->position};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u32), sizeof(vec2)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void nr_ui_item_print(nr_ui_item * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 nr_ui_item_iter(nr_ui_item * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
