// This file is auto generated by table_compiler
traversal_time * traversal_time_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key", (char *)"timeout"};
  static const char * const column_types[] = {"traversal_time_key", "f32"};
  traversal_time * instance = alloc0(sizeof(traversal_time));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 2, (u32[]){sizeof(traversal_time_key), sizeof(f32)}, (char *[]){(char *)"key", (char *)"timeout"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void traversal_time_insert(traversal_time * table, traversal_time_key * key, f32 * timeout, u64 count){
  void * array[] = {(void* )key, (void* )timeout};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void traversal_time_set(traversal_time * table, traversal_time_key key, f32 timeout){
  void * array[] = {(void* )&key, (void* )&timeout};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void traversal_time_lookup(traversal_time * table, traversal_time_key * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void traversal_time_remove(traversal_time * table, traversal_time_key * keys, u64 key_count){
  u64 indexes[key_count];
  u64 index = 0;
  u64 cnt = 0;
  while(0 < (cnt = abstract_sorttable_iter((abstract_sorttable *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, cnt);
    index = 0;
  }
}

void traversal_time_clear(traversal_time * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void traversal_time_unset(traversal_time * table, traversal_time_key key){
  traversal_time_remove(table, &key, 1);
}

bool traversal_time_try_get(traversal_time * table, traversal_time_key * key, f32 * timeout){
  void * array[] = {(void* )key, (void* )timeout};
  void * column_pointers[] = {(void *)table->key, (void *)table->timeout};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(traversal_time_key), sizeof(f32)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void traversal_time_print(traversal_time * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 traversal_time_iter(traversal_time * table, traversal_time_key * keys, size_t keycnt, traversal_time_key * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
