// This file is auto generated by table_compiler
u32_to_u32 * u32_to_u32_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key", (char *)"value"};
  static const char * const column_types[] = {"u32", "u32"};
  u32_to_u32 * instance = alloc0(sizeof(u32_to_u32));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 2, (u32[]){sizeof(u32), sizeof(u32)}, (char *[]){(char *)"key", (char *)"value"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void u32_to_u32_insert(u32_to_u32 * table, u32 * key, u32 * value, u64 count){
  void * array[] = {(void* )key, (void* )value};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void u32_to_u32_set(u32_to_u32 * table, u32 key, u32 value){
  void * array[] = {(void* )&key, (void* )&value};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void u32_to_u32_lookup(u32_to_u32 * table, u32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void u32_to_u32_remove(u32_to_u32 * table, u32 * keys, u64 key_count){
  u64 indexes[key_count];
  u64 index = 0;
  u64 cnt = 0;
  while(0 < (cnt = abstract_sorttable_iter((abstract_sorttable *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, cnt);
    index = 0;
  }
}

void u32_to_u32_clear(u32_to_u32 * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void u32_to_u32_unset(u32_to_u32 * table, u32 key){
  u32_to_u32_remove(table, &key, 1);
}

bool u32_to_u32_try_get(u32_to_u32 * table, u32 * key, u32 * value){
  void * array[] = {(void* )key, (void* )value};
  void * column_pointers[] = {(void *)table->key, (void *)table->value};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u32), sizeof(u32)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void u32_to_u32_print(u32_to_u32 * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 u32_to_u32_iter(u32_to_u32 * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
