// This file is auto generated by table_compiler
u32_lookup * u32_lookup_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key"};
  static const char * const column_types[] = {"u32"};
  u32_lookup * instance = alloc0(sizeof(u32_lookup));
  abstract_sorttable_init((abstract_sorttable * )instance, optional_name, 1, (u32[]){sizeof(u32)}, (char *[]){(char *)"key"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void u32_lookup_insert(u32_lookup * table, u32 * key, u64 count){
  void * array[] = {(void* )key};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, count);
}

void u32_lookup_set(u32_lookup * table, u32 key){
  void * array[] = {(void* )&key};
  abstract_sorttable_inserts((abstract_sorttable *) table, array, 1);
}

void u32_lookup_lookup(u32_lookup * table, u32 * keys, u64 * out_indexes, u64 count){
  abstract_sorttable_finds((abstract_sorttable *) table, keys, out_indexes, count);
}

void u32_lookup_remove(u32_lookup * table, u32 * keys, u64 key_count){
  u64 indexes[key_count];
  u64 index = 0;
  u64 cnt = 0;
  while(0 < (cnt = abstract_sorttable_iter((abstract_sorttable *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    abstract_sorttable_remove_indexes((abstract_sorttable *) table, indexes, cnt);
    index = 0;
  }
}

void u32_lookup_clear(u32_lookup * table){
  abstract_sorttable_clear((abstract_sorttable *) table);
}

void u32_lookup_unset(u32_lookup * table, u32 key){
  u32_lookup_remove(table, &key, 1);
}

bool u32_lookup_try_get(u32_lookup * table, u32 * key){
  void * array[] = {(void* )key};
  void * column_pointers[] = {(void *)table->key};
  u64 __index = 0;
  abstract_sorttable_finds((abstract_sorttable *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  u32 sizes[] = {sizeof(u32)};
  for(int i = 1; i < 1; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void u32_lookup_print(u32_lookup * table){
  abstract_sorttable_print((abstract_sorttable *) table);
}

u64 u32_lookup_iter(u32_lookup * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, u64 * indexes, u64 cnt, u64 * iterator){
  return abstract_sorttable_iter((abstract_sorttable *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
